### ISSUE TITLE
Turning angle

### ISSUE THREAD

**Issue by cmoser96** [olinrobotics/gravl#11]
Calibrate the arduino so that the software steering angle maps to the physical angle.

**Comment by ConnorNovak** [comment]
Need to rebuild actuator before this can happen.

**Comment by ConnorNovak** [comment]
Wheelbase is widened, calibration can now occur.

**Comment by cmoser96** [comment]
Bump.
Also this calibration will affect the values in Teleop.cpp and the hindbrain.

**Comment by ConnorNovak** [comment]
Nathan added a washer, so no more interference. Need to re-calibrate with new potentiometer.

**Comment by ConnorNovak** [comment]
Calibrated and successfully tested with new pot, Pull request #76
