### ISSUE TITLE
FLIR cable

### ISSUE THREAD

**Issue by cmoser96** [olinrobotics/gravl#20]
Somebody cut the USB cable on the thermal camera cable to make it "better" for drones. We need to figure out how to get a new one or attempt to repair it.

**Comment by cmoser96** [comment]
Called a bench cable:
http://www.flir.com/uploadedFiles/sUAS/Products/Vue/FLIR-VUE-QuickStartGuide.pdf

**Comment by ConnorNovak** [comment]
No longer have FLIR
