### ISSUE TITLE
Update transforms

### ISSUE THREAD

**Issue by cmoser96** [olinrobotics/gravl#22]
Actually measure the physical distances for the transforms within localization.launch

**Comment by ConnorNovak** [comment]
All transforms save new lidar updated

**Comment by ConnorNovak** [comment]
All static transforms updated; Need alternate form of odometry (encoders) in order to use ekf_localization_node; Going to jerry-rig a node to publish base_link -> map transform, skipping odom for now, using GPS coordinates.

**Comment by ConnorNovak** [comment]
Closing and opening a more relevantly named issue
